Fix tests for HTTP handlers
The refactoring in abcb000 caused the tests to fail with:

    Failed to compile cdn-broker:

    # github.com/18F/cf-cdn-service-broker/cmd/cdn-broker
    cmd/cdn-broker/main_test.go:14: undefined: buildHTTPHandler

Fix them by using the new `func bindHTTPHandlers` instead.